services:
  - type: web
    name: apteka-server
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: anthropic/claude-3-haiku
      - key: JWT_SECRET
        sync: false
      - key: SQLITE_FILE
        value: ../database/sqlite/prod.db
